### ISSUE TITLE
implement click on icon event handler

### ISSUE THREAD

**Issue by mattlub** [FACN1/city-guide#25]
a click event on the icon will turn on the visibility of the information relevant to the place associated with the icon even if its visibility was previously off

it will also change its Y location so that it gets into the users view?

**Comment by Karyum** [comment]
related to #10

**Comment by Karyum** [comment]
so do we want the user to see his pin on the map, while doing the form ?
cause i prefer the form tab would to slide up, up untill it gets to the header and the background little bit transparent
