### ISSUE TITLE
Check if the data was sent to server DB, then send to local memory, then render to map

### ISSUE THREAD

**Issue by HilbertSpitzer** [FACN1/city-guide#39]
Search the server Database and check if the data that the user just tried to add is now included in the server Database, then add all of the data in an object variable; each **value** that the user inputted will be assigned to its appropriate relevant **key** inside said object variable. Only once all of this has been done do you assign all of the data as an on click event link on its relevant icon in an organized clear manner to the eyes of the user by assigning the appropriate properties to their relevant objects

**Comment by Suuuuha** [comment]
closing this issue as we opened a new one related to it .. #91
