### ISSUE TITLE
download/create icons

### ISSUE THREAD

**Issue by mattlub** [FACN1/city-guide#44]
we need to get icons. Post suggestions here for icons/categories we need icons for.

e.g:
viewpoint: eye, 
nature: leaf symbol
history: document symbol,
food: burger/knife and fork
interesting fact: i symbol

I think we should only have a handful of categories, we could even have just one icon (in the most extreme case) i.e. a point of interest.

The problem is we haven't fully decided/agreed on exactly what is supposed to be posted on the app.

**Comment by Karyum** [comment]
i found these icons give your opinion guys (we can change the colors of the icons just fyi)
viewpoint : http://www.iconsdb.com/black-icons/visible-icon.html

information : http://www.iconsdb.com/caribbean-blue-icons/caribbean-blue-information-icons.html

nature :  http://www.iconsdb.com/black-icons/black-leaf-icons.html
              http://www.iconsdb.com/green-icons/green-tree-icons.html?page=2

history :  http://www.iconsdb.com/green-icons/green-book-icons.html
               http://www.iconsdb.com/green-icons/?search=sand

food : http://www.iconsdb.com/green-icons/green-food-icons.html
          http://www.iconsdb.com/green-icons/green-knife-icons.html

event : http://www.iconsdb.com/green-icons/green-calendar-icons.html

**Comment by mattlub** [comment]
nice. any other category suggestions?

**Comment by HilbertSpitzer** [comment]
Fun Fact:
http://pix.iemoji.com/images/emoji/apple/ios-9/256/heavy-heart-exclamation-mark-ornament.png

Good place to hang out in for families:
http://english.onlinekhabar.com/wp-content/uploads/2016/02/ride-512.png

places for couples:
https://images.vexels.com/media/users/3/138831/isolated/lists/797fcea80c93b3b2b1a93dec3c8b577c-couple-kissing-silhouette.png

good places to hang out in as a group (of friends or whatnot):
http://www.keepcalmtalklaw.co.uk/static/kctl/value-icons/value-opportunity.1426275424.png



Still under construction, maybe you should return later:
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Ambox_warning_blue_construction.svg/46px-Ambox_warning_blue_construction.svg.png

A highly dangerous area:
http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons-256/simple-red-glossy-icons-signs/095770-simple-red-glossy-icon-signs-warning-poison1.png

Be on guard:
https://www.shareicon.net/danger-weapons-exclamation-mark-shield-ortography-punctuation-exclamation-651493
http://nipgl.co.uk/wp-content/uploads/2015/06/exclamation-point-sign-red-triangle_2.png

history:
http://www.northamptontownshiplibrary.org/wp-content/uploads/2015/03/Book-Open-256-1.png

Legends or stuff to think about(not all of history is clear y'know, i'm sure many people want to know things that nobody knows for sure about):
https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Question_book-new.svg/50px-Question_book-new.svg.png

**Comment by Karyum** [comment]
- religion : church/mosque : http://www.iconsdb.com/green-icons/green-church-icons.html
http://www.iconsdb.com/green-icons/green-mosque-icons.html

- museum : museum building : http://www.iconsdb.com/green-icons/green-museum-icons.html

- hikes : feet : http://www.iconsdb.com/green-icons/?search=walk

- atm : http://www.iconsdb.com/green-icons/?search=cash

**Comment by Karyum** [comment]
i think we should have 8 maximum icons/categories and each and every icon should be a different color .
and i don't think we need viewpoint maybe a hike or walking trail instead?

**Comment by Suuuuha** [comment]
i agree on the 8 icons max (if you mean 8 different categories)

**Comment by mattlub** [comment]
I agree maybe a hike/walking trail could encompass the viewpoint one. is there a good symbol for it though?

**Comment by Suuuuha** [comment]
i loved the "fun fact" idea @HilbertSpitzer but would've chose different icon for that

**Comment by Suuuuha** [comment]
what u guys think of having the icons inside markers, with different colors for different icons/categories ?
as shown in this picture
![68747470733a2f2f7261772e6769746875622e636f6d2f6c766f6f6764742f4c6561666c65742e617765736f6d652d6d61726b6572732f6d61737465722f73637265656e73686f74732f73637265656e73686f742d736f66742e706e67](https://cloud.githubusercontent.com/assets/24496866/25666726/fc9ee50a-3029-11e7-9801-970cee0622c0.png)

**Comment by mattlub** [comment]
@Suuuuha I think it looks good, but 2 problems:
1) how would we get icons like this without making them ourselves
2) they take up a lot more space/hide more of the map

For these reasons I am relatively strongly against

**Comment by HilbertSpitzer** [comment]
"relatively strongly" against it? Excuse me dude? There's no "relative" in strongly. It's like the absolute zero, there's no relative there

**Comment by Karyum** [comment]
i think @Suuuuha icons are pretty good and pretty accurate too, i bet we could easily make those icons.
but we should make them smaller cause as @mattlub said they are kinda big 
so im relatively kinda with it

**Comment by Karyum** [comment]
we could make @Suuuuha icons smaller by using leaflet with iconSize option

**Comment by Suuuuha** [comment]
https://github.com/lvoogdt/Leaflet.awesome-markers

**Comment by HilbertSpitzer** [comment]
> i loved the "fun fact" idea @HilbertSpitzer but would've chose different icon for that

Like what @Suuuuha?

**Comment by mattlub** [comment]
closing for now, has been fixed at least temporarily
